### ISSUE TITLE
Error each time running mr-doc

### ISSUE THREAD

**Issue by Laplandia** [mr-doc/mr-doc#92]
```
$ mr-doc --help
module.js:338
    throw err;
          ^
Error: Cannot find module '../src/mr-doc'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/mr-doc/bin/mr-doc:7:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

**Comment by iwatakeshi** [comment]
@Laplandia is this from the `master` branch? Also, could you specify the version? I'm thinking that it's 2.1.0. :) 

One thing you can try doing is to re-install mr-doc because it seems the src didn't build for some odd reason. If that doesn't work then you can try cloning the master branch:

From #91, you might have an issue with cloning the master branch but I would try using the one from `master` then in the root of mr-doc's directory, run: `npm link` and then try to run help.

It should show:

```bash
Takeshis-MacBook-Pro:mr-doc iwatakeshi$ sudo npm link
Password:
/usr/local/bin/mr-doc -> /usr/local/lib/node_modules/mr-doc/bin/mr-doc
/usr/local/lib/node_modules/mr-doc -> /Users/iwatakeshi/Documents/GitHub/mr-doc
Takeshis-MacBook-Pro:mr-doc iwatakeshi$ mr-doc --help

  Usage: mr-doc [options]

  Options:

    -h, --help                   output usage information
    -V, --version                output the version number
    -e, --extension <extension>  The output files extension. Default: html
    -i, --ignore <directories>   The comma seperated list of directories to ignore. Default: test,public,static,view,views,template,templates
    -j, --template <template>    The Jade template file to use.
    -k, --kit [kit]              Marks the template as a starter-kit with a 'yes' or 'no' (optional).
    -n, --name <string>          The name of your project.
    -o, --output <output>        The directory for the generated docs. Default: <CWD>/docs
    -r, --readme <file>          The markdown file to use on the main page of the documentations. Checks the current directory for a package.json or README.md by default
    -s, --source <source>        The directory to your source.
    -t, --theme <theme>          The name of the theme to select. e.g. mr-doc-theme-cayman or cayman.

	Mr. Doc at your service!

	Here is what you can do:

	  # parse a whole folder
	  $ mr-doc --source ./lib --output ./docs

	  # parse a whole folder and use a specific template
	  $ mr-doc --template ./view/myowntpl.jade --source lib --output docs

	  # parse a whole folder and use a theme.
	  $ npm install --save mr-doc-theme-cayman
	  $ mr-doc --source ./lib --output ./docs --theme cayman

Takeshis-MacBook-Pro:mr-doc iwatakeshi$ 
```

**Comment by Laplandia** [comment]
It's 2.1.2
I have installed it using npm: `npm i -g mr-doc`
Reinstalling did not help.
I will report once I have tried to reinstall it from sources

**Comment by Laplandia** [comment]
Uninstalling the module and installing it from the git repo did help. Thanks.

**Comment by iwatakeshi** [comment]
You're welcome :). Closing issue now.
